### ISSUE TITLE
Social Buttons not working on iPhone 7

### ISSUE THREAD

**Issue by pablopeu** [tkuther/piwigo-bootstrap-darkroom#35] opened 2017-02-19 14:34 UTC
On the desktop social buttons (big 3) work as expected, on mobile (with photoswipe slideshow enabled only for mobile) you need to press the "i" (info) button so the social buttons appear, but they do not work, they just highlight themselves and nothing else happens. (IOS10.2.2/iphone 7+/safari)

I can't confirm using Chrome on the iphone because photoswipe doesn't seem to work on chrome/IOS, but the upside is that using chrome/ios solves the problem above :) so I kinda found the culprit.

whats weird is if you use the FB social button on desktop to share a photo via messenger, once the link is received you open it and inside the FB app the social buttons work as expected!!

cheers!

**Comment by tkuther** [comment] 2017-02-20 20:21
Hmm, on pwgdemo.kuther.net, the social buttons are working on iOS 10.2.1 (iPhone, iPad). Can you confirm this?

**Comment by tkuther** [comment] 2017-02-20 20:33
Update: I cannot reproduce it on your site either. Social buttons are working fine, the ones directly in photoswipe as well as those on picture.php

**Comment by pablopeu** [comment] 2017-02-20 20:43
icon does not respond to touch, if you press harder on pressure sensitive screen it launches a preview

video is uploading: https://youtu.be/DaXfXMMcrhk

**Comment by tkuther** [comment] 2017-02-20 21:39
Does the same thing happen with Bootstrap Default theme? The buttons come from it.

**Comment by pablopeu** [comment] 2017-02-20 21:47
yes the same, tonight I will try on non pressure sensitive screens and let you know. Thanks!

**Comment by pablopeu** [comment] 2017-02-21 02:53
just checked on my kids ipad1 and the buttons work, it seems on pressure sensitive phones, you need to actually press the buttons for them to work, so this is non issue after all :) 

BUT

On chrome/ios photoswipe does not work unless you configure it for both desktop and mobile, if you select the option in theme>config photoswipe for mobile only it doesn't work on chrome.

**Comment by tkuther** [comment] 2017-02-24 21:38
The chrome issue is an upstream bug with detecting chrome on iOS correctly. Maybe updating the library used for that could help. On the other hand: who uses chrome on iOS anyway :)

**Comment by tkuther** [comment] 2017-02-24 21:43
I'll close this now as the buttons are from bootstrapdefault anyway. The pressure sensitivity issue could be solved by replacing the onclick method with a ontouchstart event listener, but that should be done in bootstrapdefault.

**Closed by tkuther** 2017-02-24 21:43 UTC

**Comment by pablopeu** [comment] 2017-02-25 03:26
LMAO
