### ISSUE TITLE
videos: no thumbnails and weird behavior in mobile mode

### ISSUE THREAD

**Issue by tob123** [tkuther/piwigo-bootstrap-darkroom#192] opened 2019-01-27 13:20 UTC
Hello,

first of all: great plugin. it really helps to give piwigo a modern look and keep websites with pictures clean at the same time..!
have some issues with videos though.
url: http://piwitest.appelo.org
symptoms:
-no thumbnails
-video does get played in desktop mode ok
-in mobile mode size / offset is wrong. (i tested on android)

setup:
debian stretch, apache,php7
plugins active:
localfiles editor
gdthumb

thanks in advance.!

tob

**Comment by tkuther** [comment] 2019-01-27 14:56
Duplicate of #174

You need to fix automatic thumbnail generation for videos on your install, or manually set a representative thumbnail.

**Closed by tkuther** 2019-01-27 14:56 UTC
