### ISSUE TITLE
Video and play button offset and wrong video size

### ISSUE THREAD

**Issue by jonpas** [tkuther/piwigo-bootstrap-darkroom#174] opened 2018-09-26 14:59 UTC
On a fresh Piwigo install with this theme, there is a problem with videos.

On the picture page this is shown on PC (on mobile this is of course correct):
https://i.imgur.com/kcAu7GA.png

Inside PhotoSwipe it gets weirder, video is tiny and play button is completely offset:
https://i.imgur.com/5McWZa4.png
https://i.imgur.com/Yj8dfii.png

Am I missing some dependencies for videos (videojs is not installed) or is this a bug in recent version?
I do not care about generating thumbnails/posters, fallback images for them are just fine.

You can view above screenshotted album here: https://www.airsoftteamhornet.si/gallery/index.php?/category/4

**Comment by tkuther** [comment] 2018-09-27 16:04
Which graphics engine are you using? (GD or ImageMagick)?

It‘s broken on mobile, too, here.

**Comment by tkuther** [comment] 2018-09-28 07:26
Just out of curiosity you could try to set a representative thumbnail for one of the videos and see if that fixes the issue. I think it has to do with that.

If possible, try to switch to ImageMagick and use batch manager to generate missing derivatives.

**Comment by jonpas** [comment] 2018-09-28 10:35
How would I set one up manually? Thumbnail generation does not seem to work due to some header errors (which already seem to be fixed on master, can't find the issue right now).

**Comment by tkuther** [comment] 2018-12-26 19:20
I'm closing this because it's quite clear the issue is/was broken derivative generation

**Closed by tkuther** 2018-12-26 19:20 UTC
