### ISSUE TITLE
Empty album in galery with PHP 7.3 

### ISSUE THREAD

**Issue by franckentien** [tkuther/piwigo-bootstrap-darkroom#185] opened 2018-12-23 19:12 UTC
Hello,

I experiment an issue with PHP 7.3, piwigo 2.9.4 and your theme in 2.3.5.

On the gallery with a normal user when PHP 7.3 is activated, they are no picture was displayed.
The admin bar on the top also doesn't display.

With PHP 7.3: It's working perfectly with another theme OR if I unactive the combination of JS&CSS in Admin tools.

With PHP 7.2: the theme works perfectly.

Thanks,

**Comment by Schmidtze2** [comment] 2018-12-23 20:18
I noticed the same problem yesterday, with XAMPP and PHP 7.3. After commenting out the code in the function "process_js" (include/template.class.php) it works. JShrink_Minifier::minify adds a warning line in HTML to the created JS code always which then cause a JavaScript error of course. I think this is the same problem...

**Comment by tkuther** [comment] 2018-12-24 08:40
Hm, I can't reproduce this here. My dev site works just fine with PHP 7.3 it seems...

**Comment by tkuther** [comment] 2018-12-26 07:58
Managed to reproduce it. This is caused by a PHP Deprectated warning being merged into the combined javascript file (as shown by @Schmidtze2 ), which causes syntax errors in bootstrap's core javascript files.

So, Piwigo core isn't ready for 7.3 yet.

**Closed by tkuther** 2018-12-26 07:58 UTC
Labels: core-bug
